language: java
jdk:
  - openjdk8
dist: trusty
services:
  - postgresql
addons:
  postgresql: "9.6"
  sauce_connect: true

cache:
  directories:
    - $HOME/.gradle/

# We depend on a WildFly deployment for some of the production
# .jar files. Download it and install just above our repo.
before_script:
  - wget --no-verbose
        http://download.jboss.org/wildfly/10.1.0.Final/wildfly-10.1.0.Final.tar.gz
        -O /tmp/wildfly-10.1.0.Final.tar.gz
  - pushd ..
  - tar -xf /tmp/wildfly-10.1.0.Final.tar.gz
  - popd
  - ./scripts/travis-start-wildfly.sh

install: true

script:
  - cd psm-app
  - ./gradlew --no-daemon --console=plain
        clean
        checkstyleMain
        checkstyleTest
        cms-portal-services:build
        cms-web:apiDocs
        userhelp:html
  - ../scripts/travis-deploy-application.sh
  - ./gradlew --no-daemon --info
        test
  - cd ../

# Build the Continuous Deployment private key
before_deploy:
  - ./scripts/travis-ssh-add.sh

# Continuous Deployment
deploy:
  provider: script
  skip_cleanup: true
  script: ./scripts/deploy-ci.sh
  on:
    branch: master
